<?php
return [
	'role_structure' => [
		'developer' => [
			'acl-menu',
				'user-list',
				'user-create',
				'user-edit',
				'user-delete',
				'permissions-list',
				'permissions-create',
				'permissions-edit',
				'permissions-delete',
				'role-list',
				'role-create',
				'role-edit',
				'role-delete',

			'master-data-menu',
				'material-barang-menu',
					'material-list',
					'material-create',
					'material-edit',
					'material-delete',
					'supplier-list',
					'supplier-create',
					'supplier-edit',
					'supplier-delete',
				'kepegawaian-menu',
					'departement-list',
					'departement-create',
					'departement-edit',
					'departement-delete',
					'jabatan-list',
					'jabatan-create',
					'jabatan-edit',
					'jabatan-delete',
				'umum-menu',
					'agama-list',
					'agama-create',
					'agama-edit',
					'agama-delete',
					'status-perkawinan-list',
					'status-perkawinan-create',
					'status-perkawinan-edit',
					'status-perkawinan-delete',
					'jenis-kelamin-list',
					'jenis-kelamin-create',
					'jenis-kelamin-edit',
					'jenis-kelamin-delete',

			'profil-list',
			'profil-create',
			'profil-edit',
			'profil-delete',
		],
		'admin' => [
			'acl-menu',
				'user-list',
				'user-create',
				'user-edit',
				'user-delete',
			
			'master-data-menu',
				'material-list',
				'material-create',
				'material-edit',
				'material-delete',
				'supplier-list',
				'supplier-create',
				'supplier-edit',
				'supplier-delete',

			'profil-list',
			'profil-create',
			'profil-edit',
			'profil-delete',
		],
	]
];

?>